import '../styles/globals.css';
import Head from "next/head";
import type {AppProps} from 'next/app';
import Router from "next/router";

function MyApp({Component, pageProps, router}: AppProps): JSX.Element {

  Router.events.on('routeChangeComplete', (url: string) => {
      if (typeof window !== 'undefined') {
        console.log(url)
      }
  });


  return (
    <>
      <Head>
        <title>MyTop - наш лучший топ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
              rel="stylesheet" />
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content='ru_RU' />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
